
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClothesForHands.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Material
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Material()
    {

        this.Supplier = new HashSet<Supplier>();

    }


    public int IdMaterial { get; set; }

    public string MaterialName { get; set; }

    public int IdMaterialType { get; set; }

    public string Image { get; set; }

    public decimal Price { get; set; }

    public int StockQTY { get; set; }

    public int MinQTY { get; set; }

    public int PackQTY { get; set; }

    public int IdUnit { get; set; }

    public string Description { get; set; }



    public virtual MaterialType MaterialType { get; set; }

    public virtual Unit Unit { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Supplier> Supplier { get; set; }

}

}
