
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClothesForHands.EF
{

using System;
    using System.Collections.Generic;
    
public partial class Supplier
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Supplier()
    {

        this.Material = new HashSet<Material>();

    }


    public int IdSupplier { get; set; }

    public string SupplierName { get; set; }

    public int IdSupplierType { get; set; }

    public string INN { get; set; }

    public int Rating { get; set; }

    public System.DateTime DateStart { get; set; }



    public virtual SupplierType SupplierType { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Material> Material { get; set; }

}

}
